import { ApiProperty } from "@nestjs/swagger";
import { AlertPriority, AlertType } from "@prisma/client";
import { IsEnum, IsOptional, IsString, IsUUID, MaxLength, MinLength } from "class-validator";

export class CreateAlertDto {
  @ApiProperty()
  @IsUUID()
  studentId!: string;

  @ApiProperty({ enum: AlertType })
  @IsEnum(AlertType)
  type!: AlertType;

  @ApiProperty({ enum: AlertPriority, required: false })
  @IsOptional()
  @IsEnum(AlertPriority)
  priority?: AlertPriority;

  @ApiProperty()
  @IsString()
  @MinLength(12)
  @MaxLength(800)
  description!: string;

  @ApiProperty({ description: "Idempotency key generated by offline-capable clients." })
  @IsUUID()
  clientGeneratedId!: string;
}
